name: Deploy
# run-name: Build-Workflow
on:
  # workflow_dispatch:
  #     inputs:
  #       input-data:
  #         description: 'Add your Input Data'
  #         required: true
  push:
    branches: [master]
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - feature*

env:
  NODE_VERSION: 20.14.0


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      output_data: ${{ steps.build_id.outputs.output_data}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: install projects dependencies
        run: |
          npm ci
      - name: build project
        run: |
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-out
          path: out
          retention-days: 1
      - name: run echo
        id: build_id
        run: |
          echo "Run my First job"
          echo 'output_data=value' >> $GITHUB_OUTPUT
          echo "display secrets ${{ secrets.SECRET_VALUE }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: next-out
          path: out
      - name: List files
        run: |
          ls -la
          pwd
           mkdir -p gh-pages
           cp -r out gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages

      
